name:Deploy TODO List
on:
  push:
    branches:
    -"main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -name: Checkout
        uses: actions/checkout@v2
      -name: NPM Install
        run: npm ci
        working-directory: ./MY RESPONSIVE PROJECT
      -name: Build app
       run: npm run build
       working-directory: ./MY RESPONSIVE PROJECT
      -name: Deploy
       uses: JemesIves/github-pages-deploy-action@4.1.5
       with:
        branch: todo-list-html
        folder: MY RESPONSIVE PROJECT/build